/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QAvatar: typeof import('quasar')['QAvatar']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QDate: typeof import('quasar')['QDate']
    QDrawer: typeof import('quasar')['QDrawer']
    QField: typeof import('quasar')['QField']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QMenu: typeof import('quasar')['QMenu']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QPageSticky: typeof import('quasar')['QPageSticky']
    QPopupProxy: typeof import('quasar')['QPopupProxy']
    QSelect: typeof import('quasar')['QSelect']
    QSlider: typeof import('quasar')['QSlider']
    QSpace: typeof import('quasar')['QSpace']
    QStep: typeof import('quasar')['QStep']
    QStepper: typeof import('quasar')['QStepper']
    QStepperNavigation: typeof import('quasar')['QStepperNavigation']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    QTooltip: typeof import('quasar')['QTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
