name: CI

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  # Lint can run in parallel with Build.
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Format Check
        run: pnpm run format:check

      - name: Build Packages
        run: pnpm run build

      - name: Test
        run: pnpm run test
